(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.RedPCB300x250 = function() {
	this.initialize(img.RedPCB300x250);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Subhead2Line = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Subhead Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGICnIgMgDIABgJIALADQAFACAGAAQAFAAAEgCQAFgCACgDQADgDAAgFQAAgGgEgEQgFgEgFgDIgNgGQgFgDgFgEQgDgFAAgHQAAgIADgFQAEgGAGgBQAHgDAHAAIAJABIALADIAAAJIgKgDIgJgBQgJAAgEADQgFADAAAIQAAAEAEAEQAEADAHADIAMAFQAGAEAEAFQAEAFABAJQgBAJgEAEQgFAGgHACQgHACgGABIgMgCgAE7CjQgIgGgEgKQgEgKABgMQAAgNADgLQAFgKAIgFQAIgGALAAQAMAAAHAGQAIAFADAKQAEAJgBAMIAAAGIg5AAQAAAIADAIQADAHAGAEQAGAFAKAAIAIgCIAJgCIAGgDIAAALIgMADIgMACQgOgBgJgFgAFlB2QAAgHgCgHQgCgGgFgFQgFgEgHAAQgIAAgGAEQgGAFgDAGQgCAHAAAHIAuAAIAAAAgACMCmQgGgCgDgEQgDgFgBgDIgBgHQABgLAEgGQAFgGAIgDQAIgDAJAAIARgBIACAAIAAgFQABgKgFgGQgEgFgLAAIgNACIgMAFIAAgKIAHgDIAJgCIAJgBQAPAAAIAIQAGAHABAQIAAAmIAAAJIABAIIgLAAIAAgNQgCAFgFAEQgEADgFABQgGACgFABQgJAAgFgDgACkB9QgHAAgHACQgFACgEAFQgEADABAIQAAAHAEAEQAGAEAHAAQAJAAAFgEQAFgDADgGIACgKIABgIIAAgFIgDAAIgNABgAAHClQgHgEgDgIIAAAAIAAANIgKAAIAAh7IAKAAIAAA2IAAAAQABgDACgDQADgEAGgEQAFgDAJAAQAMAAAHAGQAJAFADAKQADALABANQAAAMgFAKQgEAKgHAGQgHAFgMABQgKAAgGgEgAAJBcQgEADgDAGQgDAFgBAGIgBANIABALQABAGADAFQADAGAEADQAFAEAHAAQAKAAAFgGQAGgFACgJQACgIAAgHQAAgJgCgIQgCgIgGgGQgFgFgKAAQgHAAgFADgAlYChQgNgHgGgOQgIgOAAgRQAAgSAIgOQAGgNANgIQANgHATAAIAIAAIAKABIAIADIgBALQgFgDgHgBQgHgBgGAAQgQAAgJAGQgLAHgGALQgFALAAAPQAAAOAFAMQAFALALAGQAKAHAQgBIAJAAIAJgCIAHgCIABAJQgDACgFABIgJACIgJABQgTAAgNgIgApACjQgHgGgEgKQgEgKAAgMQAAgNADgLQAEgKAIgFQAHgGANAAQAIAAAGADQAGAEACAEQADADABADIAAAAIAAg2IALAAIAAB7IgLAAIAAgNIAAAAQgEAIgHAEQgGAEgJAAQgLgBgJgFgAo6BeQgFAGgDAIQgBAIAAAJQAAAHABAIQADAJAFAFQAFAGALAAQAHAAAEgEQAFgDADgGQADgFABgGIABgLIgBgNQgBgGgDgFQgDgGgFgDQgEgDgHAAQgLAAgFAFgAqSCjQgJgGgDgKQgFgKABgMQAAgNAEgLQAFgKAHgFQAJgGAKAAQAMAAAHAGQAIAFAEAKQADAJAAAMIAAAGIg6AAQAAAIADAIQAEAHAFAEQAHAFAJAAIAJgCIAIgCIAGgDIAAALIgMADIgMACQgOgBgIgFgApoB2QAAgHgCgHQgDgGgEgFQgFgEgIAAQgIAAgFAEQgGAFgDAGQgDAHAAAHIAvAAIAAAAgAuZCjQgJgGgEgKQgEgKAAgMQAAgNAFgLQAEgKAIgFQAIgGALAAQALAAAIAGQAHAFAEAKQADAJABAMIAAAGIg7AAQAAAIAEAIQADAHAGAEQAHAFAIAAIAJgCIAIgCIAHgDIAAALIgMADIgNACQgNgBgIgFgAtwB2QAAgHgCgHQgCgGgFgFQgEgEgJAAQgHAAgGAEQgFAFgDAGQgEAHAAAHIAvAAIAAAAgAENCmIAAhUIAKAAIAABUgADWCmIAAhBIAAgIIAAgFIAAgGIAKAAIAAARIAGgJQADgFAEgCQAEgDAGAAIADABIAEAAIAAALIgEgBIgEAAQgGAAgEADQgEADgCAFQgDAFgBAGIgBAMIAAApgABOCmIAAhBIAAgIIAAgFIgBgGIALAAIAAARIAFgJQADgFAFgCQAEgDAFAAIADABIAEAAIAAALIgEgBIgDAAQgGAAgFADQgEADgCAFQgDAFgBAGIgBAMIAAApgAgwCmIAAhUIAKAAIAABUgAh4CmIAAhzIAKAAIAABpIAvAAIAAAKgAkBCmIAAhzIAbAAQAKAAAIADQAJACAEAGQAGAHAAALQAAAKgGAHQgEAGgLADIAAAAQALACAGAHQAHAHAAAMQAAAMgGAHQgGAIgKACQgKADgNAAgAj2CcIAMAAQAIABAHgCQAIgCAFgFQAEgFABgJQAAgKgGgFQgEgFgIgCQgIgBgJAAIgKAAgAj2BlIANAAIANgBQAGgBAFgGQAEgEABgJQgBgIgEgFQgEgEgGgBIgLgBIgQAAgAnBCmIAAhzIAdAAQAQAAAKAIQAKAJAAAPQAAALgFAIQgFAHgIAEQgJADgKABIgQAAIAAAxgAm1BrIAIAAQAJAAAHgBQAIgCAFgFQAEgFAAgLQAAgLgFgFQgHgGgKAAIgTAAgArACmIAAhUIAKAAIAABUgArvCmIAAhLIgRAAIAAgJIARAAIAAgGIABgRQABgJAFgEQAEgFALgBIAGAAIAEACIgBAJIgDgBIgFgBQgHAAgDAFQgCAEgBAGIAAALIAAAHIATAAIAAAJIgTAAIAABLgAsbCmIAAhUIALAAIAABUgAtRCmIAAhBIAAgIIAAgFIgBgGIAKAAIAAARIAGgJQADgFAEgCQAEgDAFAAIAEABIADAAIAAALIgDgBIgEAAQgGAAgEADQgFADgBAFQgDAFgBAGIgBAMIAAApgAvgCmIgrhzIAMAAIAmBoIAmhoIALAAIgsBzgAENA7IAAgNIAKAAIAAANgAgwA7IAAgNIAKAAIAAANgArAA7IAAgNIAKAAIAAANgAsbA7IAAgNIALAAIAAANgAqugIIAAh4IALAAIgBAPIAFgGQADgEAGgDQAFgEAIAAQANAAAHAGQAJAGADAKQADAJAAANQAAANgDAKQgFAKgHAFQgIAHgMgBQgJAAgHgDQgGgFgEgIIAAAAIAAAygAqVh1QgGADgCAFQgDAFgCAHIgBALIABANQACAFADAGQACAFAGADQAEADAHAAQAKAAAGgFQAFgFACgJQACgIAAgIQAAgIgCgIQgCgIgFgFQgGgGgKAAQgHAAgEAEgAPTgwQgHgFgEgKQgEgKAAgNQAAgNAEgJQADgKAIgGQAHgGANAAQAIAAAGAEQAGADADADQADAEAAACIAAAAIAAg2IALAAIAAB9IgLAAIAAgOIAAAAQgEAIgHAEQgGADgJAAQgLABgJgHgAPahzQgGAFgDAIQgBAIAAAIQAAAIABAIQADAJAGAFQAEAFALAAQAHAAAFgDQAEgDADgFQADgGABgFIABgNIgBgLQgBgHgDgFQgDgFgEgDQgFgEgHAAQgLAAgEAGgAMjgsQgGgDgDgEQgDgDgBgFIgBgHQABgKAEgGQAFgGAIgDQAIgDAJgBIARAAIACAAIAAgEQAAgLgEgFQgEgGgLAAIgNABIgMAGIAAgKIAHgDIAKgCIAIgBQAQAAAGAHQAIAIgBARIAAAlIAAAJIABAJIgKAAIAAgOQgDAFgEADQgEAEgGACQgFABgFAAQgJABgFgDgAM6hWQgGABgGACQgHACgDAEQgEAFAAAGQABAJAFADQAEADAIAAQAJAAAGgDQAEgDADgFIACgKIABgJIAAgFIgDAAIgOAAgAKjgsQgFgDgDgEQgDgDgBgFIgBgHQAAgKAFgGQAFgGAIgDQAIgDAJgBIARAAIACAAIAAgEQAAgLgEgFQgEgGgLAAIgNABIgMAGIAAgKIAIgDIAJgCIAIgBQAPAAAHAHQAIAIgBARIAAAlIAAAJIABAJIgKAAIAAgOQgDAFgEADQgEAEgGACQgEABgGAAQgJABgGgDgAK7hWQgGABgGACQgHACgDAEQgDAFgBAGQAAAJAGADQAEADAIAAQAJAAAGgDQAEgDADgFIADgKIAAgJIAAgFIgDAAIgOAAgAJzgtQgFgEAAgGQgBgHAAgIIAAgxIgQAAIAAgJIAQAAIAAgVIALgDIAAAYIATAAIAAAJIgTAAIAAA3QgBAFADAFQACADAHAAIAEAAIAFgBIABAIIgGABIgHABQgJAAgEgDgAIbgsQgFgDgEgEQgCgDgBgFIgBgHQAAgKAEgGQAGgGAIgDQAHgDAKgBIARAAIACAAIAAgEQAAgLgFgFQgEgGgKAAIgOABIgLAGIAAgKIAHgDIAJgCIAJgBQAPAAAHAHQAHAIAAARIAAAlIAAAJIABAJIgKAAIAAgOQgDAFgFADQgDAEgGACQgFABgFAAQgKABgFgDgAIzhWQgHABgGACQgGACgEAEQgDAFAAAGQAAAJAFADQAFADAHAAQAKAAAFgDQAFgDACgFIADgKIABgJIAAgFIgEAAIgNAAgAFQgtQgFgEgBgGQgBgHAAgIIAAgxIgQAAIAAgJIAQAAIAAgVIALgDIAAAYIATAAIAAAJIgTAAIAAA3QAAAFACAFQADADAGAAIAFAAIAEgBIACAIIgGABIgIABQgJAAgDgDgADBgsQgFgDgDgEQgDgDgCgFIgBgHQABgKAFgGQAFgGAHgDQAJgDAIgBIARAAIACAAIAAgEQABgLgEgFQgFgGgLAAIgMABIgNAGIAAgKIAIgDIAJgCIAIgBQAQAAAHAHQAHAIAAARIAAAlIAAAJIABAJIgLAAIAAgOQgCAFgEADQgEAEgGACQgFABgGAAQgIABgGgDgADZhWQgHABgGACQgGACgDAEQgEAFAAAGQAAAJAFADQAFADAIAAQAIAAAGgDQAFgDACgFIADgKIAAgJIAAgFIgDAAIgNAAgAgMgwQgIgFgEgKQgFgKABgNQAAgNAEgJQAEgKAIgGQAJgGAJAAQAMAAAHAGQAIAFADAKQAEAKAAALIAAAGIg5AAQAAAIAEAHQACAIAHAEQAFAEAJAAIAIgBIAJgBIAGgEIAAALIgLADIgNABQgMABgJgHgAAdhbQgBgIgCgHQgCgGgEgEQgFgFgIAAQgHAAgFAFQgGAEgDAGQgDAHAAAIIAuAAIAAAAgAi/grIgLgCIABgKIAKADQAGACAGgBQAFABAEgCQAEgCADgEQADgCAAgGQgBgGgDgDQgFgEgFgCIgMgHQgGgCgFgFQgEgFAAgHQAAgIAEgGQAEgEAHgCQAFgDAIAAIAJABIALADIgBAJIgJgDIgJgBQgIAAgFADQgFADgBAIQABAFAEADQAEADAHACIALAGQAHAEAEAFQAEAGABAHQgBAKgFAEQgEAGgHADQgHABgGAAIgNgBgAlmgwQgJgFgEgKQgDgKAAgNQAAgNAEgJQAEgKAJgGQAHgGAMAAQALAAAIAGQAHAFADAKQAEAKAAALIAAAGIg6AAQAAAIADAHQAEAIAFAEQAHAEAJAAIAIgBIAJgBIAHgEIAAALIgNADIgMABQgNABgJgHgAk9hbQAAgIgBgHQgDgGgFgEQgEgFgIAAQgHAAgHAFQgFAEgDAGQgDAHAAAIIAuAAIAAAAgAoUgwQgIgFgEgKQgEgKAAgNQABgNAEgJQAEgKAIgGQAIgGALAAQALAAAIAGQAIAFADAKQADAKAAALIAAAGIg5AAQgBAIAEAHQADAIAGAEQAGAEAKAAIAIgBIAJgBIAGgEIAAALIgMADIgMABQgOABgJgHgAnqhbQAAgIgCgHQgCgGgFgEQgEgFgJAAQgHAAgGAFQgGAEgDAGQgCAHAAAIIAuAAIAAAAgAuHgwQgIgGgEgKQgFgKAAgMQAAgLAFgKQAEgLAIgFQAJgHANAAQAOAAAJAHQAJAFAEALQAEAKAAALQAAAMgEAKQgEAKgJAGQgJAGgOAAQgNAAgJgGgAuAh0QgGAFgDAHQgEAIAAAKQAAAKAEAIQADAIAGAFQAHAEAIAAQAJAAAHgEQAGgFADgIQADgIABgKQgBgKgDgIQgDgHgGgFQgHgFgJAAQgIAAgHAFgAvogxQgMgIgIgNQgHgNAAgTQAAgRAHgNQAIgOAMgHQANgIATAAIAIABIAKAAIAIADIAAALQgGgDgHgBQgHgCgGABQgPAAgKAHQgLAGgGALQgFALAAAOQAAAQAFAKQAGAMAKAGQALAGAPAAIAJAAIAJgBIAIgEIAAALQgDACgFABIgJABIgJAAQgTAAgNgHgAOlgrIAAg0QAAgMgEgHQgFgHgLAAQgJAAgGAFQgGAFgCAGQgCAIAAAHIAAAvIgKAAIAAhBIAAgKIgBgKIAKAAIAAAPIAAAAIAFgIQADgEAFgCQAGgDAIAAQALAAAHAFQAFADAEAIQACAHAAAKIAAA2gAGngrIAAh0IAdAAQAUAAANAIQANAGAFANQAGANAAARQAAAWgIAMQgJANgPAGQgPAFgTABgAGyg1IAKAAQAQgBAMgEQANgFAGgKQAHgMAAgRQgBgRgGgLQgGgLgLgEQgKgEgNAAIgRAAgAEMgrIAAhCIAAgHIAAgHIgBgFIALAAIAAAQIAFgJQADgDAFgDQAEgDAFAAIADAAIAEABIAAALIgEgBIgDAAQgHAAgDADQgFADgCAFQgCAFgCAGIgBAMIAAAqgABpgrIAAh0IAcAAQARAAAJAIQALAIgBARQAAAKgEAIQgGAHgIAEQgIAEgLgBIgQAAIAAAzgAB0hoIAIAAQAKABAHgCQAIgBAEgFQAFgFAAgKQAAgLgGgGQgGgGgLAAIgTAAgAhOgrIgdhVIAMAAIAXBJIAZhJIALAAIgeBVgAiDgrIAAhVIALAAIAABVgAjmgrIAAg0QAAgMgFgHQgFgHgLAAQgJAAgFAFQgGAFgCAGQgCAIAAAHIAAAvIgLAAIAAhBIAAgKIgBgKIALAAIAAAPIAAAAIAEgIQADgEAGgCQAFgDAJAAQALAAAGAFQAGADADAIQADAHAAAKIAAA2gAmUgrIAAgzQAAgHgCgGQgBgHgEgDQgFgEgIAAQgJAAgFAFQgGAFgCAHQgDAIAAAIIAAAtIgLAAIAAh9IALAAIAAA2IAAAAQAEgHAHgEQAHgFAIAAQAMAAAGAFQAGAFADAHQADAJAAAKIAAAzgApRgrIAAhCIAAgHIAAgHIgBgFIALAAIAAAQIAFgJQADgDAFgDQADgDAGAAIADAAIAEABIAAALIgEgBIgDAAQgHAAgDADQgFADgCAFQgDAFAAAGIgBAMIAAAqgArQgrIAAg4QAAgHgCgFQgBgFgEgCQgEgDgHAAQgGAAgFAEQgFACgDAIQgEAGABALIAAAvIgLAAIAAg4QAAgHgCgFQgBgFgEgCQgEgDgHAAQgGAAgFAEQgFACgDAIQgDAGgBALIAAAvIgKAAIAAhBIAAgKIAAgKIAKAAIAAAOIAAAAIAEgHQADgDAFgDQAGgDAIAAIAJABQAEACAEAEQAEADABAIIABAAQADgIAHgEQAHgGAKAAQAJAAAFAEQAHADACAHQADAGAAAIIAAA7gAiDiXIAAgOIALAAIAAAOg");
	this.shape.setTransform(105.2,21);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Subhead Box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#737473").ss(2,1,1).p("A3PkVMAufAAAIAAIrMgufAAAg");
	this.shape_1.setTransform(135.4,21.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("A3PEWIAAorMAufAAAIAAIrg");
	this.shape_2.setTransform(135.4,21.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Subhead2Line, new cjs.Rectangle(-14.4,-7,299.5,57.5), null);


(lib.Subhead = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Subhead Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACXERIgLgDIAAgKIALADQAFACAGAAQAGAAAEgCQAEgCACgDQADgDABgFQgBgGgEgDQgEgFgGgCIgMgGQgGgDgEgEQgEgFAAgIQAAgHAEgGQAEgFAGgCQAGgCAHAAIAJABIAMACIgBAJIgJgCIgKgBQgIAAgEACQgGAEAAAHQAAAFAFADQAEADAGADIAMAGQAGADAEAFQAFAGAAAIQgBAJgEAFQgFAFgHADQgGACgGAAIgNgBgABLEMQgIgFgFgLQgEgKABgMQAAgNAEgKQAEgKAJgGQAHgFAMAAQALAAAIAFQAHAGADAKQAEAJAAALIAAAGIg6AAQAAAJAEAHQACAIAHADQAGAFAJAAIAIgBIAJgCIAHgDIAAALIgMADIgNABQgNAAgJgGgAB0DgQAAgHgCgIQgBgGgGgEQgEgFgIABQgHgBgHAFQgFAEgDAHQgDAGAAAIIAuAAIAAAAgAhkEPQgGgCgDgEQgCgEgBgEIgBgHQAAgKAEgHQAGgFAIgDQAHgDAKgBIAQAAIADAAIAAgFQAAgLgFgFQgEgGgKABIgOABIgLAFIAAgKIAHgDIAJgBIAJgBQAPgBAHAIQAHAHAAARIAAAlIAAAJIABAJIgKAAIAAgNQgDAEgEAEQgEADgGACQgFACgFAAQgKAAgFgDgAhMDmQgHABgGACQgGACgEAEQgDAEAAAHQAAAIAFADQAFAEAIAAQAJAAAFgEQAFgDACgFIADgKIABgJIAAgEIgEAAIgNAAgAjpEOQgGgEgEgHIgBAAIAAANIgKAAIAAh8IAKAAIAAA2IABAAQAAgCAEgEQACgEAHgDQAFgEAIABQAMAAAIAFQAIAGAEAKQADAKAAANQAAAMgEAKQgEALgIAFQgHAGgMAAQgJAAgHgEgAjmDGQgFADgDAGQgDAEgBAHIgCAMIACAMQABAGADAFQADAFAFADQAFAEAHAAQAKAAAFgFQAFgFADgJQACgIAAgIQAAgJgCgHQgDgJgFgFQgFgGgKABQgIgBgEAEgApIELQgNgIgHgOQgHgNAAgSQAAgRAHgOQAHgOANgHQANgIASAAIAJABIAKABIAIADIgBALQgFgDgIgCQgGgBgHAAQgPAAgKAHQgLAGgFALQgGAMABAOQAAAPAEALQAGALAKAHQALAGAPAAIAJgBIAJgBIAIgDIABAKQgDACgFABIgKABIgJABQgSAAgNgHgAAdEQIAAhUIAKAAIAABUgAgZEQIAAhBIAAgIIAAgGIgBgFIALAAIAAAQIAFgJQADgEAEgDQADgCAGAAIADAAIAEABIAAAKIgEAAIgEAAQgFAAgDACQgFADgCAFQgDAFAAAGIgBANIAAApgAiiEQIAAhBIAAgIIAAgGIAAgFIAKAAIAAAQIAFgJQADgEAFgDQAEgCAGAAIADAAIAEABIAAAKIgEAAIgEAAQgGAAgEACQgEADgDAFQgCAFgBAGIgBANIAAApgAkhEQIAAhUIAKAAIAABUgAlpEQIAAh0IALAAIAABqIAvAAIAAAKgAnyEQIAAh0IAcAAQAJAAAIADQAJACAFAHQAFAGAAALQAAALgFAHQgFAGgKACIAAABQALABAGAIQAHAGAAAMQgBAMgFAIQgHAHgKADQgKADgMAAgAnnEGIANAAQAHAAAIgCQAHgBAGgGQAEgFAAgIQAAgLgFgEQgFgFgIgCQgHgBgJAAIgLAAgAnmDPIANAAIAMgBQAHgCAEgFQAFgFAAgIQAAgJgFgEQgDgEgHgBIgKgBIgQAAgAqxEQIAAh0IAdAAQAQABAKAHQAKAJAAAQQAAALgGAHQgFAIgHADQgJAEgKAAIgRAAIAAAygAqmDUIAJAAQAJAAAHgBQAHgCAFgEQAFgGAAgKQAAgLgGgGQgGgFgLAAIgTAAgAAdClIAAgOIAKAAIAAAOgAkhClIAAgOIAKAAIAAAOgAG4A5QgIgGgDgJQgEgKAAgNQAAgNADgJQAEgKAHgFQAIgHAMAAQAJABAGADQAFADADAEQADADAAADIABAAIAAg2IALAAIAAB7IgLAAIAAgOIgBAAQgEAIgGAFQgHADgJAAQgLAAgIgGgAG+gKQgFAGgDAGQgCAJAAAIQAAAIACAIQADAJAFAEQAFAGAKAAQAHAAAFgDQAFgEADgFQACgFABgGIACgMIgCgMQgBgGgCgEQgDgGgFgDQgFgDgHgBQgKABgFAFgAFlA5QgIgGgEgJQgEgKAAgNQAAgNAFgJQAEgKAIgFQAIgHALAAQALAAAIAHQAHAFAEAKQADAIAAAMIAAAFIg5AAQAAAJADAHQADAHAGAFQAHAEAJAAIAIgBIAJgCIAGgEIAAAMIgMADIgMABQgOAAgJgGgAGPANQAAgIgCgFQgCgHgFgEQgEgEgJgBQgHABgGAEQgFAFgDAGQgDAFAAAIIAuAAIAAAAgABeA5QgIgGgFgJQgDgKAAgNQAAgNAEgJQAEgKAJgFQAHgHAMAAQALAAAHAHQAIAFADAKQAEAIAAAMIAAAFIg6AAQAAAJAEAHQACAHAHAFQAGAEAJAAIAIgBIAJgCIAGgEIAAAMIgLADIgNABQgNAAgJgGgACHANQAAgIgCgFQgBgHgGgEQgEgEgIgBQgIABgFAEQgGAFgDAGQgDAFAAAIIAuAAIAAAAgAiEA5QgIgGgEgJQgEgKAAgNQAAgNADgJQAEgKAIgFQAIgHAMAAQAIABAGADQAFADADAEQADADABADIABAAIAAg2IAKAAIAAB7IgKAAIAAgOIgBAAQgEAIgHAFQgGADgJAAQgMAAgHgGgAh/gKQgFAGgDAGQgCAJAAAIQAAAIACAIQADAJAFAEQAGAGAKAAQAGAAAFgDQAFgEADgFQADgFABgGIACgMIgCgMQgBgGgDgEQgDgGgFgDQgFgDgGgBQgKABgGAFgAk1A9QgGgDgDgEQgDgEgBgEIgBgHQABgLAEgFQAFgHAIgCQAIgDAJgBIARgBIACAAIAAgEQABgJgFgGQgEgFgLgBIgNACIgMAGIAAgKIAHgDIAJgDIAJgBQAPAAAIAIQAGAHABAQIAAAmIAAAJIABAIIgLAAIAAgOQgCAGgFADQgEADgFACQgGACgFAAQgJAAgFgCgAkdATQgHABgHABQgFADgEAEQgEAEABAHQAAAIAEAEQAGADAHAAQAJAAAFgDQAFgEADgFIACgKIABgIIAAgGIgDAAIgNABgAm0A9QgGgDgDgEQgDgEgBgEIgBgHQABgLAEgFQAFgHAIgCQAIgDAJgBIARgBIACAAIAAgEQABgJgFgGQgFgFgKgBIgNACIgMAGIAAgKIAHgDIAJgDIAJgBQAPAAAIAIQAGAHAAAQIAAAmIAAAJIACAIIgLAAIAAgOQgDAGgEADQgEADgFACQgGACgFAAQgJAAgFgCgAmdATQgHABgFABQgGADgEAEQgDAEAAAHQAAAIAEAEQAFADAIAAQAJAAAFgDQAFgEADgFIACgKIABgIIAAgGIgDAAIgOABgAnlA7QgEgEgBgGQgCgGABgIIAAgxIgQAAIAAgJIAQAAIAAgUIALgDIAAAXIASAAIAAAJIgSAAIAAA2QgBAGACAEQAEAEAFAAIAGgBIAEgBIABAJIgFABIgIABQgJAAgEgEgAo9A9QgGgDgDgEQgDgEgBgEIgBgHQABgLAEgFQAFgHAIgCQAIgDAJgBIARgBIACAAIAAgEQAAgJgEgGQgEgFgLgBIgNACIgMAGIAAgKIAHgDIAKgDIAIgBQAQAAAGAIQAIAHgBAQIAAAmIAAAJIABAIIgKAAIAAgOQgDAGgEADQgEADgGACQgFACgFAAQgJAAgFgCgAomATQgGABgGABQgHADgDAEQgEAEAAAHQABAIAFAEQAEADAIAAQAJAAAGgDQAEgEADgFIACgKIABgIIAAgGIgDAAIgOABgAE3A9IAAhUIALAAIAABUgAEIA9IAAhLIgRAAIAAgJIARAAIAAgFIABgRQABgJAFgFQAFgFAKAAIAGAAIAEABIgBAKIgDgBIgFgBQgHAAgDAEQgCAEAAAGIAAAMIAAAGIATAAIAAAJIgTAAIAABLgADdA9IAAhUIAKAAIAABUgACmA9IAAhAIAAgIIAAgGIAAgGIAKAAIAAARIAFgJQADgEAEgDQAEgCAGgBIAEABIADAAIAAAMIgDgCIgFAAQgFABgFADQgEACgCAGQgCADgCAHIgBALIAAAqgAAYA9IgrhyIANAAIAkBnIAnhnIAKAAIgrBygAizA9IAAg0QAAgKgEgHQgFgIgLAAQgKAAgFAGQgFAEgCAGQgDAHAAAIIAAAuIgLAAIAAg/IAAgKIAAgLIAKAAIAAAPIAAAAIAFgHQADgEAGgCQAFgEAIAAQALABAGAEQAHAEACAIQADAHABAIIAAA2gAqxA9IAAhyIAcAAQAVAAANAHQAMAHAGANQAGANgBAQQAAAVgIAMQgJAOgOAFQgPAGgTAAgAqmAzIAJAAQARAAALgFQANgEAGgLQAHgLAAgSQAAgQgGgLQgHgKgKgEQgKgFgNAAIgRAAgAE3gtIAAgOIALAAIAAAOgADdgtIAAgOIAKAAIAAAOgAlhhyIAAh4IALAAIgBAQIAFgHQADgDAGgEQAFgDAIAAQANAAAHAFQAJAGADAKQADAKAAANQAAAMgDAKQgFALgHAFQgIAGgMAAQgJAAgHgEQgGgEgEgIIAAAAIAAAxgAlIjfQgGADgCAFQgDAFgCAHIgBAMIABAMQACAGADAFQACAFAGADQAEAEAHAAQAKAAAGgFQAFgFACgJQACgIAAgIQAAgJgCgHQgCgJgFgFQgGgGgKABQgHgBgEAEgAKdiXQgFgEgBgGQgBgGAAgIIAAgyIgQAAIAAgJIAQAAIAAgUIALgEIAAAYIATAAIAAAJIgTAAIAAA3QAAAGACAEQADAEAGAAIAFAAIAEgCIACAIIgGACIgIABQgJAAgDgEgAIOiWQgFgCgDgEQgDgEgCgEIgBgHQABgKAFgHQAFgFAHgEQAJgCAIgBIARAAIACAAIAAgFQABgLgEgFQgFgGgLABIgMABIgNAGIAAgLIAIgDIAJgBIAIgBQAQAAAHAHQAHAIAAAQIAAAlIAAAJIABAJIgLAAIAAgNQgCAEgEAEQgEAEgGABQgFACgGAAQgIAAgGgDgAImi/QgHAAgGACQgGADgDAEQgEAEAAAHQAAAIAFADQAFAEAIAAQAIAAAGgEQAFgDADgFIACgKIAAgJIAAgEIgCAAIgOAAgAFAiZQgIgFgEgLQgFgKABgMQAAgNAEgKQAEgKAIgGQAJgFAKAAQAMAAAHAFQAIAGADAJQAEAKAAALIAAAGIg6AAQAAAJAEAHQACAIAHADQAGAFAJAAIAIgBIAJgCIAGgDIAAAKIgLAEIgNABQgNAAgJgGgAFqjFQgBgHgCgIQgCgGgEgEQgFgFgIABQgIgBgFAFQgGAFgDAGQgDAGAAAIIAvAAIAAAAgACNiUIgLgDIABgKIAKADQAGACAGAAQAFAAAEgCQAEgBADgEQADgDAAgFQgBgGgDgDQgFgEgFgDIgMgGQgGgDgFgEQgEgFAAgIQAAgHAEgGQAEgFAHgCQAFgDAIABIAJABIALACIgBAJIgJgCIgJgBQgIAAgFACQgFAEgBAHQABAFAEADQAEADAHADIALAGQAHADAEAFQAEAGABAIQgBAJgFAFQgEAFgHADQgHACgGAAIgNgBgAgZiZQgJgFgEgLQgDgKAAgMQAAgNAEgKQAEgKAJgGQAHgFAMAAQAKAAAIAFQAHAGAEAJQADAKAAALIAAAGIg5AAQAAAJADAHQAEAIAFADQAHAFAJAAIAHgBIAJgCIAHgDIAAAKIgNAEIgLABQgNAAgJgGgAAPjFQAAgHgBgIQgDgGgFgEQgEgFgHABQgHgBgHAFQgFAFgDAGQgDAGAAAIIAtAAIAAAAgAjHiZQgIgFgEgLQgEgKAAgMQABgNAEgKQAEgKAIgGQAIgFALAAQALAAAIAFQAIAGADAJQADAKAAALIAAAGIg5AAQgBAJAEAHQADAIAGADQAGAFAKAAIAIgBIAJgCIAGgDIAAAKIgMAEIgMABQgOAAgJgGgAidjFQAAgHgCgIQgCgGgFgEQgEgFgJABQgHgBgGAFQgGAFgCAGQgDAGAAAIIAuAAIAAAAgAo6iZQgIgHgEgKQgFgKAAgLQAAgMAFgKQAEgKAIgGQAJgGANAAQAOAAAJAGQAJAGAEAKQAEAKAAAMQAAALgEAKQgEAKgJAHQgJAGgOAAQgNAAgJgGgAozjeQgGAFgDAIQgEAIAAAKQAAAJAEAJQADAHAGAFQAHAFAIAAQAJAAAHgFQAGgFADgHQADgJABgJQgBgKgDgIQgDgIgGgFQgHgEgJAAQgIAAgHAEgAqbiaQgMgIgIgOQgHgNAAgSQAAgSAHgNQAIgOAMgHQANgIATAAIAIABIAKABIAIADIAAAKQgGgCgHgBQgHgCgGAAQgPAAgKAHQgLAGgGALQgFALAAAPQAAAPAFALQAGALAKAHQALAGAPAAIAJgBIAJgBIAIgDIAAAKQgDACgFABIgJACIgJAAQgTAAgNgHgAJZiVIAAhCIAAgHIAAgGIgBgGIALAAIAAARIAFgJQADgEAFgDQAEgDAFABIADAAIAEABIAAAKIgEgBIgDAAQgHAAgDADQgFAEgCAEQgCAGgCAFIgBANIAAApgAG2iVIAAhzIAcAAQARAAAJAHQALAJgBAQQAAALgEAHQgGAIgIADQgIAEgLAAIgQAAIAAAygAHBjRIAIAAQAKAAAHgBQAIgCAEgEQAFgGAAgKQAAgLgGgGQgGgFgLAAIgTAAgAD+iVIgdhVIAMAAIAXBJIAZhJIALAAIgeBVgADJiVIAAhVIALAAIAABVgABmiVIAAgzQAAgNgFgGQgFgIgLABQgJAAgFAEQgGAFgCAHQgCAHAAAHIAAAvIgLAAIAAhBIAAgKIgBgKIALAAIAAAQIAAAAIAEgIQADgEAGgDQAFgCAJAAQALgBAGAFQAGAEADAIQADAGAAAKIAAA2gAhHiVIAAgyQAAgIgCgGQgBgGgEgEQgFgDgIAAQgJAAgFAEQgGAGgCAHQgDAHAAAIIAAAtIgLAAIAAh8IALAAIAAA2IAAAAQAEgHAHgFQAHgEAIAAQAMAAAGAEQAGAFADAIQADAIAAALIAAAygAkEiVIAAhCIAAgHIAAgGIgBgGIALAAIAAARIAFgJQADgEAFgDQADgDAGABIADAAIAEABIAAAKIgEgBIgDAAQgHAAgDADQgFAEgCAEQgDAGAAAFIgBANIAAApgAmDiVIAAg4QAAgGgCgFQgBgFgEgDQgEgCgHAAQgGgBgFAEQgFADgDAHQgEAHABAKIAAAvIgLAAIAAg4QAAgGgCgFQgBgFgEgDQgEgCgHAAQgGgBgFAEQgFADgDAHQgDAHgBAKIAAAvIgKAAIAAhBIAAgKIAAgKIAKAAIAAAPIAAAAIAEgHQADgEAFgDQAGgCAIAAIAJABQAEACAEAEQAEADABAIIABAAQADgIAHgFQAHgGAKABQAJAAAFADQAHAEACAGQADAGAAAJIAAA6gADJkAIAAgOIALAAIAAAOg");
	this.shape.setTransform(71.9,31.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Subhead Box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#737473").ss(2,1,1).p("AvtmeIfbAAIAAM9I/bAAg");
	this.shape_1.setTransform(87.2,32.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AvtGfIAAs9IfbAAIAAM9g");
	this.shape_2.setTransform(87.2,32.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Subhead, new cjs.Rectangle(-14.4,-10,203.3,85), null);


(lib.LogoBox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Logo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVAbIgDguIAAAAIgGAUIgKAaIgEAAIgJgaIgHgUIgCAuIgHAAIAEg1IAJAAIAJAaIAFARIAAAAIAGgRIAJgaIAJAAIADA1g");
	this.shape.setTransform(83.9,28.7,0.326,0.326);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgDAbIAAgvIgQAAIAAgGIAnAAIAAAGIgQAAIAAAvg");
	this.shape_1.setTransform(82.2,28.7,0.326,0.326);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AKUEOQgXgHgRgNQgQgMgLgSQgKgUAAgYQAAgpAVgZQAXgYAfgKQAegMAngDQAlgDAfAAIAWAAIAAgKQAAglgWgSQgWgSgoAAQgbAAgaAJQgbAJgUARIgjgjQAZgaAlgNQAigNAmAAQBLAAAhAjQAhAkAABGIAACRIACAeQAAAMADARIg2AAQgCgLgBgPIAAgZIgCAAQgQAZgcASQgcARgnAAQgYgBgYgGgAKjB5QggAPAAAiQAAAgAWANQAVAOAgAAQAYAAASgIQASgJANgOQALgMAIgTQAGgRABgXIAAgVIg4AAQg3AAgfAPgAhDEOQgYgHgQgNQgRgMgKgSQgKgTAAgZQAAgqAWgYQAWgYAfgKQAfgMAmgDQAlgDAeAAIAWAAIAAgKQAAgkgWgTQgWgSgnAAQgbAAgaAJQgbAJgUARIgjgjQAZgaAlgNQAigNAlAAQBLAAAhAjQAhAkAABGIAACRIACAeIADAdIg2AAQgDgLAAgPIAAgZIgCAAQgQAZgcASQgcARgmAAQgYgBgYgGgAg0B5QgfAPAAAiQAAAgAVANQAVAOAgAAQAWAAAUgIQARgJANgOQANgOAGgRQAGgTABgVIAAgVIg4AAQg2AAgfAPgAqZEBQgigUgQgdIgCAAIAAA8Ig4AAIAAogIA4AAIAAEBIACAAQAYgcAegPQAegPAlAAQAnAAAhANQAgANAYAYQAXAZANAeQANAgAAAnQAAAngNAfQgNAggXAZQgWAYgfANQgfAOgkAAQgsgBgjgTgAqGgQQgWAKgQAQQgQASgIAWQgJAXAAAaQAAAbAJAXQAIAXAQAQQAQASAWAIQAWALAbgBQAbABAWgLQAWgJAQgRQAQgQAIgXQAIgWAAgcQAAgbgIgWQgIgWgQgSQgQgPgWgLQgVgJgcAAQgcAAgVAJgASmEMIAAjLQAAgqgTgYQgTgYgnAAQgbAAgVAJQgUAKgMAQQgNATgGAWQgGAYAAAdIAACkIg4AAIAAkCIgBgpIgCgmIA1AAIACA4IABAAQAGgMAKgLQAJgLAQgKQAPgJASgGQATgFAUAAQAgAAAZAKQAZALAPARQAQATAHAYQAIAaAAAeIAADQgAHLEMIAAlRIA4AAIAAFRgADgEMIAAkCQAAgVgBgUIgCgmIA2AAIABA4IABAAQAHgMAKgLQAKgMAOgJQARgKAQgFQATgFAUAAIALABQAFAAAHADIgEA4QgOgEgQAAQg0AAgXAgQgYAiAAA7IAACkgAliEMIAAkCQAAgVgBgUIgCgmIA1AAIACA4IABAAQAHgMAKgLQAIgLAQgKQAPgJASgGQATgFAUAAIALABQAFAAAHADIgEA4QgPgEgPAAQg0AAgXAgQgYAiAAA7IAACkgAuSEMIAAlRIA5AAIAAFRgAzdEMIAAn9IA9AAIAAHFIDpAAIAAA4g");
	this.shape_2.setTransform(40.9,31.7,0.326,0.326);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhZBaIAAi0ICzAAIAAC0g");
	this.shape_3.setTransform(10.5,10.6,0.326,0.326);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiwCzIAAllIFhAAIAAFlg");
	this.shape_4.setTransform(10.5,10.7,0.326,0.326);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BF082A").s().p("AjrDuIAAnbIHWAAIAAHbg");
	this.shape_5.setTransform(10.6,10.6,0.326,0.326);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#737473").s().p("AgWAvIAAhcIAsAAIAABcg");
	this.shape_6.setTransform(5.2,1.5,0.326,0.326);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_7.setTransform(1.5,5.3,0.326,0.326);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_8.setTransform(1.5,8,0.326,0.326);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_9.setTransform(1.5,10.6,0.326,0.326);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_10.setTransform(1.5,13.3,0.326,0.326);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_11.setTransform(1.5,16.1,0.326,0.326);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#737473").s().p("AgWAuIAAhbIAsAAIAABbg");
	this.shape_12.setTransform(5.2,19.8,0.326,0.326);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#737473").s().p("AgWAuIAAhbIAtAAIAABbg");
	this.shape_13.setTransform(7.9,19.8,0.326,0.326);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#737473").s().p("AgVAuIAAhbIAsAAIAABbg");
	this.shape_14.setTransform(10.5,19.8,0.326,0.326);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#737473").s().p("AgVAuIAAhbIAsAAIAABbg");
	this.shape_15.setTransform(13.2,19.8,0.326,0.326);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#737473").s().p("AgVAuIAAhbIAsAAIAABbg");
	this.shape_16.setTransform(15.9,19.8,0.326,0.326);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#737473").s().p("AguAYIAAgvIBdAAIAAAvg");
	this.shape_17.setTransform(19.6,13.3,0.326,0.326);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_18.setTransform(19.6,16,0.326,0.326);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_19.setTransform(19.6,10.6,0.326,0.326);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#737473").s().p("AgtAXIAAgtIBbAAIAAAtg");
	this.shape_20.setTransform(19.6,7.9,0.326,0.326);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#737473").s().p("AgtAWIAAgsIBbAAIAAAsg");
	this.shape_21.setTransform(19.6,5.2,0.326,0.326);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#737473").s().p("AgVAvIAAhcIArAAIAABcg");
	this.shape_22.setTransform(15.8,1.5,0.326,0.326);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#737473").s().p("AgVAvIAAhcIAsAAIAABcg");
	this.shape_23.setTransform(13.2,1.5,0.326,0.326);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#737473").s().p("AgVAvIAAhcIAsAAIAABcg");
	this.shape_24.setTransform(10.5,1.5,0.326,0.326);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#737473").s().p("AgWAvIAAhcIAtAAIAABcg");
	this.shape_25.setTransform(7.9,1.5,0.326,0.326);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ao3EGQglgRgXgdQgXgdgKgkQgLgmAAgqIAAk6IA9AAIAAEyQAAAgAHAcQAFAbAQAYQAPAVAZAOQAaAOAmAAQAlAAAagOQAZgNAPgWQAPgWAHgdQAGggAAgcIAAkyIA9AAIAAE6QAAAqgKAmQgLAmgXAbQgXAegkAQQgkARg1AAQg2AAgjgRgAHFEMQgWgGgSgNQgRgNgKgSQgKgTAAgZQAAgpAWgYQAVgYAggLQAfgMAngDQAkgDAfAAIAWAAIAAgKQAAglgWgRQgWgTgoAAQgbAAgaAJQgaAJgVASIgjgkQAZgaAlgNQAigNAmAAQBLAAAhAjQAhAjABBIIAACQQgBAPACAPQABAMACARIg2AAQgCgKgBgQIAAgZIgBAAQgQAagdARQgcAQgmAAQgcAAgVgGgAHVB3QggAPgBAjQABAfAVAOQAWANAfAAQAZAAARgIQATgIAMgOQAMgNAHgTQAGgRABgXIAAgVIg4AAQg2AAgfAPgAAKELQgQgIgLgPQgKgOgDgVQgDgVAAgbIAAi4IhKAAIAAgvIBKAAIAAhgIA2AAIAABgIBkAAIAAAvIhkAAIABDGQABAOAFALQAGAKAKAGQAJAHATAAQAMAAAOgDQAKgDAOgGIACAzQgNAGgTAEQgUACgOAAQgeAAgSgHgACmEKIAAkBQAAgXgCgTIgBglIA2AAIABA3IABAAQAHgNAKgKQAKgMAPgJQANgJATgFQARgGAWAAIAMABIALADIgEA5QgOgFgQAAQgzAAgZAhQgXAhABA7IAACkgAjOEKIAAogIA3AAIAAIgg");
	this.shape_26.setTransform(46.3,17.6,0.326,0.326);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Logo Box
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#737473").ss(2,1,1).p("ApwqiIThAAIAAVFIzhAAg");
	this.shape_27.setTransform(39.4,-8.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("ApwKjIAA1FIThAAIAAVFg");
	this.shape_28.setTransform(39.4,-8.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.LogoBox, new cjs.Rectangle(-24.1,-77.3,127,137), null);


(lib.HeadlineVert3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Headline
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkJMeQgNgKgHgQQgHgQAAgUQAAgLACgMQACgNAEgLIAdAEIgFAPIgDAMIgBAPQAAAJADAJQACAJAHAGQAGAGAMAAQAMgBAIgJQAIgKAGgOQAHgOAIgOQAIgOAOgKQANgJAWgBQAXABAPALQAOAKAHATQAHASAAAWQgBAMgCAMIgHAWIgdgDQAEgJADgMQADgNABgMQAAgKgEgKQgEgKgHgHQgJgHgNAAQgOAAgJAKQgJAJgGAPIgOAcQgIAOgMAJQgMAKgUAAQgUAAgOgJgABQKgIAAh2IAcAAIAABWIBAAAIAAhSIAcAAIAABSIBlAAIAAAggAjBKAQgSgKgKgRQgLgRAAgXQAAgbAMgPQAMgQAVgHQAUgGAbAAIAABzQAQAAAMgHQAMgHAHgNQAGgMAAgOQAAgKgCgKIgHgSIgHgMIAeAAIAHAUQADAMABATQgBAdgKATQgLASgUAJQgTAJgbAAQgYAAgTgJgAi5IaQgLAFgGAJQgGAJAAANQAAAOAHAKQAHAJAKAFQALAEAKABIAAhTQgMAAgKAEgABGIAIAAghIAhAAIAAAhgACLH/IAAgeICiAAIAAAegAiKHRQgLgHgGgLQgGgMgDgNQgCgNAAgLIAAgQIAAgQQgVgBgKAKQgLAJAAAWQAAANAFAMQAEAMAIAKIgaABQgGgLgFgNQgEgOAAgPQAAgiARgQQARgPAhAAIBDAAIAVAAIALgBIAAAbIgVAAIAAABQAFAEAGAGQAFAHAEAKQAEAKABANQAAASgGANQgFANgLAIQgLAIgSAAQgPgBgKgHgAiQF3IAAAKIABAPQABAKADAJQADAJAGAGQAGAHALAAQAJAAAGgFQAFgEAEgHQACgHAAgHQAAgPgFgKQgGgKgJgFQgKgFgMAAIgOAAIgBAJgACLGqIAAgdIAaAAIAAAAQgOgHgIgPQgHgOAAgRQAAgfASgPQASgPAhAAIBgAAIAAAeIhUAAQgcAAgOAHQgOAIgBATQAAARAIALQAJALAPAFQAPAFATAAIBLAAIAAAegAjkEdIAAgcIAZAAIAAAAQgNgHgIgLQgIgLAAgOIABgKIABgJIAbAAIgCAIIgBAIQAAAVASALQARAMAfAAIBKAAIAAAegACxDrQgTgHgLgQQgLgPAAgYQAAgVAHgNQAHgNAMgGIAAgBIhjAAIAAgeIDuAAIAAAdIgXAAIAAAAQAHAEAGAIQAGAHAEALQAEALAAAPQAAASgHANQgIANgMAJQgNAIgPAEQgQAEgQAAQgXAAgSgIgADwDRQALgCAJgGQAJgFAGgJQAGgIAAgMQAAgRgKgLQgJgKgOgFQgOgFgNAAQgQAAgNAFQgOAFgJALQgJALAAAQQAAAQAJAKQAIAKAOAEQAOAFAPgBQAJABALgDgAi/ClQgTgKgLgTQgLgSAAgZIACgUIAEgRIAZADIgFARIgCAPQABARAIAMQAJALANAGQAOAGAQAAQAPABANgGQAOgGAJgMQAJgLAAgUQAAgHgCgJQgCgJgFgHIAbgCQAEAKABAJIACATQgBAYgLATQgLASgUALQgTAKgXAAQgZAAgTgKgAkwAVIAAgdIBjAAIAAgBQgNgIgHgNQgHgOAAgRQAAgfATgPQASgPAhABIBgAAIAAAeIhUAAQgcgBgOAIQgPAIgBATQAAARAJALQAIALAPAFQAPAFAUAAIBLAAIAAAdgABQg0IAAg1IC4hFIi4hEIAAg1IDdAAIAAAgIi/AAIAAABIC/BJIAAAfIi/BJIAAABIC/AAIAAAggAkgkHIAAggIDCAAIAAhdIAcAAIAAB9gACwlcQgTgKgKgTQgLgSAAgZQAAgZALgTQAKgSATgKQAUgKAYgBQAYABATAKQATAKAMATQALASAAAZQAAAYgLATQgMASgTALQgTAKgYAAQgYAAgUgKgAC/nRQgOAGgIALQgJAMAAAQQAAAQAJALQAIALAOAGQAOAGAPAAQAPAAAOgFQAOgFAJgMQAJgLAAgRQAAgSgJgLQgJgLgOgGQgOgFgPAAQgPAAgOAGgAjBmiQgSgJgKgRQgLgRAAgXQAAgbAMgQQAMgQAVgGQAUgHAbAAIAAB0QAQAAAMgIQAMgHAHgMQAGgMAAgOQAAgKgCgLIgHgSIgHgLIAeAAIAHAUQADALABAUQgBAdgKASQgLATgUAJQgTAJgbAAQgYAAgTgKgAi5oHQgLAFgGAIQgGAJAAANQAAAPAHAJQAHAJAKAFQALAFAKABIAAhUQgMAAgKAFgACLofIAAgcIAZAAIAAAAQgMgHgIgLQgIgLAAgOIAAgKIACgJIAaAAIgCAIIAAAIQAAAVARALQASAMAfAAIBJAAIAAAegAjSpNQgLgHgGgNQgFgNAAgQQAAgLACgJIAEgRIAaACIgEAKIgDAMIgBAKQAAALAFAJQAFAIAKAAQAKAAAFgHQAGgHAFgLIAKgUQAFgLAKgHQAJgHAPAAQARAAAMAIQALAIAFANQAGANAAAOQAAAMgCALQgCAMgFAKIgbgCQAEgGACgHIAEgNIABgLQABgHgDgHQgCgHgFgEQgFgFgJAAQgIAAgGAHQgGAHgFAKIgKAVQgGALgJAHQgJAHgNAAQgRAAgLgIgACvqZQgSgJgLgRQgKgRAAgXQAAgbAMgQQAMgQAUgGQAVgHAaAAIAAB0QAQAAAMgIQAMgHAHgMQAHgMAAgOQAAgKgDgLIgGgSIgHgLIAeAAIAGAUQAEALAAAUQAAAdgLASQgLATgTAJQgUAJgaAAQgZAAgSgKgAC2r+QgKAFgGAIQgGAJAAANQAAAPAHAJQAHAJAKAFQAKAFALABIAAhUQgNAAgKAFgAjSrIQgLgIgGgNQgFgNAAgQQAAgKACgJIAEgSIAaADIgEAJIgDAMIgBAKQAAAMAFAIQAFAIAKABQAKgBAFgHQAGgHAFgKIAKgVQAFgKAKgHQAJgHAPAAQARAAAMAIQALAIAFANQAGAMAAAPQAAALgCAMQgCALgFAKIgbgBQAEgGACgHIAEgNIABgLQABgHgDgHQgCgHgFgFQgFgFgJAAQgIABgGAHQgGAHgFAKIgKAVQgGAKgJAHQgJAHgNAAQgRAAgLgHg");
	this.shape.setTransform(34.5,82.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Red Box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#737473").ss(2,1,1).p("AnB3PIODAAMAAAAufIuDAAg");
	this.shape_1.setTransform(36.5,134.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C8102E").s().p("AnBXPMAAAgudIODAAMAAAAudg");
	this.shape_2.setTransform(36.5,134.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HeadlineVert3, new cjs.Rectangle(-9.5,-15.7,92,299.5), null);


(lib.HeadlineVert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Headline
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkJMeQgNgKgHgQQgHgQAAgUQAAgLACgMQACgNAEgLIAdAEIgFAPIgDAMIgBAPQAAAJADAJQACAJAHAGQAGAGAMAAQAMgBAIgJQAIgKAGgOQAHgOAIgOQAIgOAOgKQANgJAWgBQAXABAPALQAOAKAHATQAHASAAAWQgBAMgCAMIgHAWIgdgDQAEgJADgMQADgNABgMQAAgKgEgKQgEgKgHgHQgJgHgNAAQgOAAgJAKQgJAJgGAPIgOAcQgIAOgMAJQgMAKgUAAQgUAAgOgJgABQKgIAAh2IAcAAIAABWIBAAAIAAhSIAcAAIAABSIBlAAIAAAggAjBKAQgSgKgKgRQgLgRAAgXQAAgbAMgPQAMgQAVgHQAUgGAbAAIAABzQAQAAAMgHQAMgHAHgNQAGgMAAgOQAAgKgCgKIgHgSIgHgMIAeAAIAHAUQADAMABATQgBAdgKATQgLASgUAJQgTAJgbAAQgYAAgTgJgAi5IaQgLAFgGAJQgGAJAAANQAAAOAHAKQAHAJAKAFQALAEAKABIAAhTQgMAAgKAEgABGIAIAAghIAhAAIAAAhgACLH/IAAgeICiAAIAAAegAiKHRQgLgHgGgLQgGgMgDgNQgCgNAAgLIAAgQIAAgQQgVgBgKAKQgLAJAAAWQAAANAFAMQAEAMAIAKIgaABQgGgLgFgNQgEgOAAgPQAAgiARgQQARgPAhAAIBDAAIAVAAIALgBIAAAbIgVAAIAAABQAFAEAGAGQAFAHAEAKQAEAKABANQAAASgGANQgFANgLAIQgLAIgSAAQgPgBgKgHgAiQF3IAAAKIABAPQABAKADAJQADAJAGAGQAGAHALAAQAJAAAGgFQAFgEAEgHQACgHAAgHQAAgPgFgKQgGgKgJgFQgKgFgMAAIgOAAIgBAJgACLGqIAAgdIAaAAIAAAAQgOgHgIgPQgHgOAAgRQAAgfASgPQASgPAhAAIBgAAIAAAeIhUAAQgcAAgOAHQgOAIgBATQAAARAIALQAJALAPAFQAPAFATAAIBLAAIAAAegAjkEdIAAgcIAZAAIAAAAQgNgHgIgLQgIgLAAgOIABgKIABgJIAbAAIgCAIIgBAIQAAAVASALQARAMAfAAIBKAAIAAAegACxDrQgTgHgLgQQgLgPAAgYQAAgVAHgNQAHgNAMgGIAAgBIhjAAIAAgeIDuAAIAAAdIgXAAIAAAAQAHAEAGAIQAGAHAEALQAEALAAAPQAAASgHANQgIANgMAJQgNAIgPAEQgQAEgQAAQgXAAgSgIgADwDRQALgCAJgGQAJgFAGgJQAGgIAAgMQAAgRgKgLQgJgKgOgFQgOgFgNAAQgQAAgNAFQgOAFgJALQgJALAAAQQAAAQAJAKQAIAKAOAEQAOAFAPgBQAJABALgDgAi/ClQgTgKgLgTQgLgSAAgZIACgUIAEgRIAZADIgFARIgCAPQABARAIAMQAJALANAGQAOAGAQAAQAPABANgGQAOgGAJgMQAJgLAAgUQAAgHgCgJQgCgJgFgHIAbgCQAEAKABAJIACATQgBAYgLATQgLASgUALQgTAKgXAAQgZAAgTgKgAkwAVIAAgdIBjAAIAAgBQgNgIgHgNQgHgOAAgRQAAgfATgPQASgPAhABIBgAAIAAAeIhUAAQgcgBgOAIQgPAIgBATQAAARAJALQAIALAPAFQAPAFAUAAIBLAAIAAAdgABQg0IAAg1IC4hFIi4hEIAAg1IDdAAIAAAgIi/AAIAAABIC/BJIAAAfIi/BJIAAABIC/AAIAAAggAkgkHIAAggIDCAAIAAhdIAcAAIAAB9gACwlcQgTgKgKgTQgLgSAAgZQAAgZALgTQAKgSATgKQAUgKAYgBQAYABATAKQATAKAMATQALASAAAZQAAAYgLATQgMASgTALQgTAKgYAAQgYAAgUgKgAC/nRQgOAGgIALQgJAMAAAQQAAAQAJALQAIALAOAGQAOAGAPAAQAPAAAOgFQAOgFAJgMQAJgLAAgRQAAgSgJgLQgJgLgOgGQgOgFgPAAQgPAAgOAGgAjBmiQgSgJgKgRQgLgRAAgXQAAgbAMgQQAMgQAVgGQAUgHAbAAIAAB0QAQAAAMgIQAMgHAHgMQAGgMAAgOQAAgKgCgLIgHgSIgHgLIAeAAIAHAUQADALABAUQgBAdgKASQgLATgUAJQgTAJgbAAQgYAAgTgKgAi5oHQgLAFgGAIQgGAJAAANQAAAPAHAJQAHAJAKAFQALAFAKABIAAhUQgMAAgKAFgACLofIAAgcIAZAAIAAAAQgMgHgIgLQgIgLAAgOIAAgKIACgJIAaAAIgCAIIAAAIQAAAVARALQASAMAfAAIBJAAIAAAegAjSpNQgLgHgGgNQgFgNAAgQQAAgLACgJIAEgRIAaACIgEAKIgDAMIgBAKQAAALAFAJQAFAIAKAAQAKAAAFgHQAGgHAFgLIAKgUQAFgLAKgHQAJgHAPAAQARAAAMAIQALAIAFANQAGANAAAOQAAAMgCALQgCAMgFAKIgbgCQAEgGACgHIAEgNIABgLQABgHgDgHQgCgHgFgEQgFgFgJAAQgIAAgGAHQgGAHgFAKIgKAVQgGALgJAHQgJAHgNAAQgRAAgLgIgACvqZQgSgJgLgRQgKgRAAgXQAAgbAMgQQAMgQAUgGQAVgHAaAAIAAB0QAQAAAMgIQAMgHAHgMQAHgMAAgOQAAgKgDgLIgGgSIgHgLIAeAAIAGAUQAEALAAAUQAAAdgLASQgLATgTAJQgUAJgaAAQgZAAgSgKgAC2r+QgKAFgGAIQgGAJAAANQAAAPAHAJQAHAJAKAFQAKAFALABIAAhUQgNAAgKAFgAjSrIQgLgIgGgNQgFgNAAgQQAAgKACgJIAEgSIAaADIgEAJIgDAMIgBAKQAAAMAFAIQAFAIAKABQAKgBAFgHQAGgHAFgKIAKgVQAFgKAKgHQAJgHAPAAQARAAAMAIQALAIAFANQAGAMAAAPQAAALgCAMQgCALgFAKIgbgBQAEgGACgHIAEgNIABgLQABgHgDgHQgCgHgFgFQgFgFgJAAQgIABgGAHQgGAHgFAKIgKAVQgGAKgJAHQgJAHgNAAQgRAAgLgHg");
	this.shape.setTransform(37.5,82.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Red Box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#737473").ss(2,1,1).p("EgHkgoWIPJAAMAAABQtIvJAAg");
	this.shape_1.setTransform(40,243.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C8102E").s().p("EgHkAoXMAAAhQsIPJAAMAAABQsg");
	this.shape_2.setTransform(40,243.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HeadlineVert, new cjs.Rectangle(-9.5,-15.7,99,518.5), null);


(lib.CATBox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_425 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(425).call(this.frame_425).wait(1));

	// Arrow
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguAgIAwg/IAtAAIgwA/g");
	this.shape.setTransform(175.6,18.4,0.944,0.944);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACAgIgwg/IAtAAIAwA/g");
	this.shape_1.setTransform(175.6,12.3,0.944,0.944);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[]},45).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},151).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},154).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[]},5).to({state:[{t:this.shape_1},{t:this.shape}]},5).wait(1));

	// CTA
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AK0A5QgHgIAAgNIAAgrIgQAAIAAgQIAQAAIAAgRIAXgIIAAAZIAUAAIAAAQIgUAAIAAAnQAAAGACAEQACAFAGAAIAGgBQAAAAABAAQABgBAAAAQABAAAAAAQABgBAAAAIABASIgHACIgJAAQgOAAgHgHgAJoA/IgNgDIACgSIAKAEQAGABAGABIAGgBQADgBADgDQACgCAAgEQAAgFgEgCIgJgEIgMgEQgGgDgEgFQgEgFAAgIQAAgJAFgGQAFgGAIgCQAHgDAJAAIAOABIALACIgCARIgJgDIgLgBIgGABQgDAAgCADQgCACAAADQAAAEAEABIAKAFIALADQAGADAEAGQAEAEAAAKQAAAKgFAGQgGAGgIADQgIADgJAAIgNgBgAIQA9QgGgDgFgGQgEgGAAgHQAAgKAEgGQAEgGAHgDQAGgEAIAAIAPgCIAMAAQAAgIgFgFQgFgEgKAAQgHAAgHADQgGACgGAEIgBgTQAHgDAIgBQAIgCAHAAQAUgBAJAJQAJAJgBASIAAALIABAMIAAAKIAAAJIABAKIgUAAIgBgHIAAgGQgDAFgEAEIgKAEQgFACgFAAQgIAAgHgDgAIkAXQgFABgEAEQgFADAAAGQAAAGAEACQAEACAHABQAFAAAEgCQAEgDACgDQADgEABgEQABgFAAgFIgKAAIgLABgAFNA/IgMgDIABgSIALAEQAFABAGABIAHgBQADgBACgDQADgCAAgEQAAgFgEgCIgKgEIgLgEQgGgDgEgFQgEgFAAgIQAAgJAFgGQAEgGAIgCQAIgDAJAAIANABIALACIgBARIgKgDIgLgBIgGABQgDAAgCADQgCACAAADQAAAEAEABIAKAFIAMADQAFADAEAGQAEAEAAAKQAAAKgFAGQgFAGgIADQgJADgJAAIgNgBgAEXA5QgHgIAAgNIAAgrIgRAAIAAgQIARAAIAAgRIAWgIIAAAZIAUAAIAAAQIgUAAIAAAnQAAAGACAEQACAFAHAAIAFgBQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAIABASIgIACIgJAAQgNAAgHgHgAB8A9QgHgDgEgGQgFgGAAgHQAAgKAEgGQAEgGAHgDQAHgEAHAAIAPgCIAMAAQAAgIgEgFQgFgEgKAAQgHAAgHADQgHACgGAEIAAgTQAGgDAIgBQAIgCAIAAQATgBAJAJQAJAJAAASIAAALIAAAMIAAAKIABAJIAAAKIgUAAIAAgHIgBgGQgDAFgEAEIgJAEQgFACgGAAQgHAAgHgDgACQAXQgGABgEAEQgEADAAAGQAAAGAEACQAEACAGABQAFAAAEgCQAEgDADgDQADgEABgEQABgFgBgFIgJAAIgLABgAilA7QgGgEgDgHQgDgIAAgKIAAg1IAWAAIAAAtIABALQABAFADAEQADAFAHAAQAGAAAEgEQAEgCACgEQACgFABgFIABgJIAAgpIAWAAIAABVIgVAAIAAgMQgGAHgHADQgHAEgJAAQgKAAgHgFgAkEA6QgKgGgGgKQgFgKAAgMQAAgPAGgJQAGgKAKgGQAKgGANABQANgBAKAGQAKAGAGAKQAGAJAAAPQAAAMgFAKQgGAKgKAGQgKAGgOAAQgOAAgKgGgAj4gEQgFAEgCAFQgDAFAAAGQAAAIACAHQACAGAFAFQAEAFAJAAQAIAAAFgFQAFgFACgGQACgHAAgIQAAgGgDgGQgCgFgFgDQgFgEgHAAQgHAAgFAEgAn0A6QgIgHgDgKQgEgLAAgLQAAgMAEgKQADgKAIgGQAIgHAOABQAIAAAGADQAGACAFAHIABAAIAAgyIAWAAIAAB9IgWAAIAAgKQgFAHgHACQgGADgIAAQgOAAgIgGgAnkgEQgEAEgCAGIgBANIABAMQACAGAEAFQAEAFAIAAQAHAAAFgFQAEgFACgFQACgHAAgGQAAgHgDgGQgBgGgFgEQgEgEgIAAQgHAAgEAEgAG4A+IAAh0IBBAAIAAASIgpAAIAAAdIAnAAIAAASIgnAAIAAAzgADMA+IAAhVIAUAAIAAATIAAAAQABgEADgFQADgFAFgEQAFgDAHAAIADAAIAEAAIAAAXIgFgCIgFAAQgHAAgEAEQgEACgBAGQgCAFAAAHIgBAKIAAAggAAYA+IAAh0IAeAAQANAAALADQALADAHAIQAHAHAAAOQAAAOgGAHQgGAIgKAEQgLADgMAAIgKAAIAAAtgAAwAAIAIAAQAGAAAFgCQAFgBADgEQADgDAAgIQAAgGgDgEQgDgEgFgCQgFgCgGAAIgIAAgAhOA+IAAhVIAUAAIAAATIAAAAQABgEADgFQADgFAFgEQAFgDAHAAIADAAIAEAAIAAAXIgFgCIgFAAQgHAAgEAEQgEACgBAGQgCAFAAAHIgBAKIAAAggAlPA+IAAgvIgqhFIAbAAIAcAxIAcgxIAZAAIgqBFIAAAvgAonA+IAAguIAAgLQgBgFgDgEQgDgEgHAAQgGAAgEADQgEADgCADQgDAEAAAGIgBAJIAAAqIgXAAIAAhVIAWAAIAAALQAFgHAHgDQAHgDAJAAQALgBAGAFQAHAEADAIQADAIAAAIIAAA3gAqKA+IAAhVIAXAAIAABVgArYA+IAAh0IBBAAIAAASIgqAAIAAAdIAoAAIAAASIgoAAIAAAzgAqKgnIAAgVIAXAAIAAAVg");
	this.shape_2.setTransform(89.6,14.9);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(426));

	// Grey Box
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#737473").s().p("A4MCcIAAk3MAwYAAAIAAE3g");
	this.shape_3.setTransform(154.9,15.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(426));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,309.7,31.3);


// stage content:
(lib.ULSingleSource300x2504 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_363 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(363).call(this.frame_363).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#737473").ss(2,1,1).p("A3RzXMAujAAAMAAAAmvMgujAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(364));

	// Layer 10
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#737473").s().p("AnxF/IAAr8IPjAAIAAL8g");
	this.shape_1.setTransform(174.8,288.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(364));

	// CTA Box
	this.instance = new lib.CATBox();
	this.instance.parent = this;
	this.instance.setTransform(198.2,99.1,1,1,0,0,0,100.9,15.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(107).to({x:101.9,y:99.7},6).wait(42).to({y:160.2},6).wait(113).to({y:99.7},5).wait(42).to({x:198.9},6).wait(37));

	// Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_155 = new cjs.Graphics().p("AsmUyIAA3vIZNAAIAAXvg");
	var mask_graphics_156 = new cjs.Graphics().p("AsmVNIAA3vIZNAAIAAXvg");
	var mask_graphics_157 = new cjs.Graphics().p("AsmVoIAA3vIZNAAIAAXvg");
	var mask_graphics_158 = new cjs.Graphics().p("AsmWDIAA3vIZNAAIAAXvg");
	var mask_graphics_159 = new cjs.Graphics().p("AsmWfIAA3vIZNAAIAAXvg");
	var mask_graphics_160 = new cjs.Graphics().p("AsmW6IAA3vIZNAAIAAXvg");
	var mask_graphics_161 = new cjs.Graphics().p("AsmXVIAA3vIZNAAIAAXvg");
	var mask_graphics_274 = new cjs.Graphics().p("AsmXVIAA3vIZNAAIAAXvg");
	var mask_graphics_275 = new cjs.Graphics().p("AsmW1IAA3vIZNAAIAAXvg");
	var mask_graphics_276 = new cjs.Graphics().p("AsmWWIAA3vIZNAAIAAXvg");
	var mask_graphics_277 = new cjs.Graphics().p("AsmV2IAA3vIZNAAIAAXvg");
	var mask_graphics_278 = new cjs.Graphics().p("AsmVXIAA3vIZNAAIAAXvg");
	var mask_graphics_279 = new cjs.Graphics().p("AsmU3IAA3vIZNAAIAAXvg");
	var mask_graphics_289 = new cjs.Graphics().p("AsmU3IAA3vIZNAAIAAXvg");
	var mask_graphics_290 = new cjs.Graphics().p("ArFU3IAA3vIZOAAIAAXvg");
	var mask_graphics_291 = new cjs.Graphics().p("AoxU4IAA3vIZOAAIAAXvg");
	var mask_graphics_292 = new cjs.Graphics().p("AmdU4IAA3vIZNAAIAAXvg");
	var mask_graphics_293 = new cjs.Graphics().p("AkKU4IAA3vIZNAAIAAXvg");
	var mask_graphics_294 = new cjs.Graphics().p("Ah3U4IAA3vIZOAAIAAXvg");
	var mask_graphics_295 = new cjs.Graphics().p("AAcU4IAA3vIZPAAIAAXvg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(155).to({graphics:mask_graphics_155,x:70.8,y:133}).wait(1).to({graphics:mask_graphics_156,x:70.8,y:135.7}).wait(1).to({graphics:mask_graphics_157,x:70.8,y:138.4}).wait(1).to({graphics:mask_graphics_158,x:70.8,y:141.1}).wait(1).to({graphics:mask_graphics_159,x:70.8,y:143.9}).wait(1).to({graphics:mask_graphics_160,x:70.8,y:146.6}).wait(1).to({graphics:mask_graphics_161,x:70.8,y:149.3}).wait(113).to({graphics:mask_graphics_274,x:70.8,y:149.3}).wait(1).to({graphics:mask_graphics_275,x:70.8,y:146.1}).wait(1).to({graphics:mask_graphics_276,x:70.8,y:143}).wait(1).to({graphics:mask_graphics_277,x:70.8,y:139.8}).wait(1).to({graphics:mask_graphics_278,x:70.8,y:136.7}).wait(1).to({graphics:mask_graphics_279,x:70.8,y:133.5}).wait(10).to({graphics:mask_graphics_289,x:70.8,y:133.5}).wait(1).to({graphics:mask_graphics_290,x:90.5,y:133.5}).wait(1).to({graphics:mask_graphics_291,x:105.3,y:133.6}).wait(1).to({graphics:mask_graphics_292,x:120,y:133.6}).wait(1).to({graphics:mask_graphics_293,x:134.8,y:133.6}).wait(1).to({graphics:mask_graphics_294,x:149.5,y:133.6}).wait(1).to({graphics:mask_graphics_295,x:164.3,y:133.7}).wait(69));

	// Logo
	this.instance_1 = new lib.LogoBox();
	this.instance_1.parent = this;
	this.instance_1.setTransform(239.6,210.7,1,1,0,0,0,42.4,20.4);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(123).to({x:66.5},6).wait(160).to({x:239.5},6).wait(69));

	// Mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A7IIuIAAxaMA2RAAAIAARag");
	mask_1.setTransform(166.3,35.3);

	// Headline 2
	this.instance_2 = new lib.HeadlineVert3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(346.2,48.5,1,1,90,0,0,40,243.6);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(140).to({_off:false},0).wait(32).to({x:40.7},5).wait(128).to({y:138.6},6).wait(5).to({visible:false},0).wait(48));

	// Mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_274 = new cjs.Graphics().p("A5zGDIAAsGMAznAAAIAAMGg");
	var mask_2_graphics_275 = new cjs.Graphics().p("A5zK5IAAsGMAznAAAIAAMGg");
	var mask_2_graphics_276 = new cjs.Graphics().p("A5zKaIAAsGMAznAAAIAAMGg");
	var mask_2_graphics_277 = new cjs.Graphics().p("A5zJ7IAAsGMAznAAAIAAMGg");
	var mask_2_graphics_278 = new cjs.Graphics().p("A5zJcIAAsGMAznAAAIAAMGg");
	var mask_2_graphics_279 = new cjs.Graphics().p("A5zGEIAAsGMAznAAAIAAMGg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(274).to({graphics:mask_2_graphics_274,x:160.8,y:106.8}).wait(1).to({graphics:mask_2_graphics_275,x:160.8,y:69.7}).wait(1).to({graphics:mask_2_graphics_276,x:160.8,y:66.6}).wait(1).to({graphics:mask_2_graphics_277,x:160.8,y:63.5}).wait(1).to({graphics:mask_2_graphics_278,x:160.8,y:60.4}).wait(1).to({graphics:mask_2_graphics_279,x:160.8,y:75.8}).wait(85));

	// Subhead 2 Line
	this.instance_3 = new lib.Subhead2Line();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-123.2,118.6,1,1,0,0,0,111.4,22);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(187).to({_off:false},0).to({x:126.3,y:118.1},6).wait(101).to({visible:false},0).wait(70));

	// Subhead
	this.instance_4 = new lib.Subhead();
	this.instance_4.parent = this;
	this.instance_4.setTransform(182.9,42.3,1,1,0,0,0,71.7,32.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(140).to({x:86.1},5).wait(192).to({x:183.1},6).wait(21));

	// Headline 1
	this.instance_5 = new lib.HeadlineVert();
	this.instance_5.parent = this;
	this.instance_5.setTransform(47.9,99,1,1,0,0,0,38.3,83.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(91).to({x:47.8,y:-98},6).wait(58).to({visible:false},0).wait(166).to({x:-49.2,visible:true},0).to({x:47.8},6).wait(26).to({y:99},6).wait(5));

	// Red PCB
	this.instance_6 = new lib.RedPCB300x250();
	this.instance_6.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(364));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,407,518.6);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 20,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/RedPCB300x250.jpg", id:"RedPCB300x250"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;